#cloud-config
autoinstall:
  version: 1

  identity:
    hostname: temp-host
    username: vimaru
    password: "$6$MZHng35SzKqXyh1s$KglZ6tlUuxZ//ANjqsZ12dHTYC6jBKNsafg4Ap2GADbTG22yHiCsinjjUFTV2NV0bfsnV/svuzCwzZt7mrsYO0"  # vimaru

  locale: vi_VN
  timezone: Asia/Ho_Chi_Minh

  packages:
    - git
    - curl
    - ibus-unikey
    - ttf-mscorefonts-installer
    - snapd

  late-commands:
    # ===== LẤY SỐ TỪ SERVER =====
    - curtin in-target -- bash -c '
        NUM=$(curl -s https://noname-daxl.onrender.com);
        HOST="PC-$NUM";

        echo "$HOST" > /etc/hostname;
        hostnamectl set-hostname "$HOST";

        sed -i "s/127.0.1.1.*/127.0.1.1 $HOST/" /etc/hosts;
      '

    # ===== IBUS =====
    - curtin in-target -- ibus restart
    - curtin in-target -- ibus-daemon -drx

    # ===== SNAP =====
    - curtin in-target -- systemctl enable --now snapd
    - curtin in-target -- systemctl enable --now snapd.apparmor

    # ===== ONLYOFFICE =====
    - curtin in-target -- snap install onlyoffice-desktopeditors

    # ===== CÀI ZALO =====
    - curtin in-target -- bash -c '
        mkdir -p /home/student/Applications;
        chown student:student /home/student/Applications;

        cd /home/student/Applications;
        git clone https://github.com/realdtn2/zalo-linux-2026.git;

        cd zalo-linux-2026;
        chmod +x install.sh;
        ./install.sh;
      '